"""add dim_ozon_campaign

Revision ID: b81f3ce45f30
Revises: 5ff7cb984e5e
Create Date: 2026-03-19 16:18:33.039100
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b81f3ce45f30'
down_revision: Union[str, None] = '5ff7cb984e5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_ozon_campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('campaign_type', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('daily_budget', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('payment_type', sa.String(), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'campaign_id', name='uq_ozon_campaign_shop')
    )
    op.create_index(op.f('ix_dim_ozon_campaigns_campaign_id'), 'dim_ozon_campaigns', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_dim_ozon_campaigns_id'), 'dim_ozon_campaigns', ['id'], unique=False)
    op.create_index(op.f('ix_dim_ozon_campaigns_shop_id'), 'dim_ozon_campaigns', ['shop_id'], unique=False)
    op.create_table('dim_ozon_campaign_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.BigInteger(), nullable=False),
    sa.Column('sku', sa.BigInteger(), nullable=False),
    sa.Column('bid', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['shop_id', 'campaign_id'], ['dim_ozon_campaigns.shop_id', 'dim_ozon_campaigns.campaign_id'], name='fk_ozon_campaign_products_campaign', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'campaign_id', 'sku', name='uq_ozon_camp_prod_sku')
    )
    op.create_index(op.f('ix_dim_ozon_campaign_products_campaign_id'), 'dim_ozon_campaign_products', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_dim_ozon_campaign_products_id'), 'dim_ozon_campaign_products', ['id'], unique=False)
    op.create_index(op.f('ix_dim_ozon_campaign_products_shop_id'), 'dim_ozon_campaign_products', ['shop_id'], unique=False)
    op.create_index(op.f('ix_dim_ozon_campaign_products_sku'), 'dim_ozon_campaign_products', ['sku'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dim_ozon_campaign_products_sku'), table_name='dim_ozon_campaign_products')
    op.drop_index(op.f('ix_dim_ozon_campaign_products_shop_id'), table_name='dim_ozon_campaign_products')
    op.drop_index(op.f('ix_dim_ozon_campaign_products_id'), table_name='dim_ozon_campaign_products')
    op.drop_index(op.f('ix_dim_ozon_campaign_products_campaign_id'), table_name='dim_ozon_campaign_products')
    op.drop_table('dim_ozon_campaign_products')
    op.drop_index(op.f('ix_dim_ozon_campaigns_shop_id'), table_name='dim_ozon_campaigns')
    op.drop_index(op.f('ix_dim_ozon_campaigns_id'), table_name='dim_ozon_campaigns')
    op.drop_index(op.f('ix_dim_ozon_campaigns_campaign_id'), table_name='dim_ozon_campaigns')
    op.drop_table('dim_ozon_campaigns')
    # ### end Alembic commands ###

